---
- name: ping server
  ping:

- name: download and install the zabbix package
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
  become: true

- name: update apt packages
  apt:
    force_apt_get: true
    update_cache: yes
    upgrade: dist
  become: true

- name: install zabbix
  apt:
    pkg:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: install mysql
  apt:
    name:
      - mysql-server
      - python3-pip
      - libmysqlclient-dev
      - python3-dev
      - python3-mysqldb
    state: present

- name: enable and reload mysql
  systemd:
    name: mysql
    enabled: true
    masked: no
    state: restarted

- name: create mysql user
  community.mysql.mysql_user:
    name: zabbix
    password: "{{ password_db }}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: create mysql database
  community.mysql.mysql_db:
    name: zabbix
    encoding: utf8mb4
    collation: utf8mb4_bin
    state: present

- name: search for server.sql
  stat:
    path: /usr/share/zabbix-sql-scripts/mysql/server.sql
  register: result

- name: extract .gz into /tmp
  shell:
    cmd: gunzip /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  when: not result.stat.exists

- name: import preset (will not be executed if server.sql existed before Extracting)
  community.mysql.mysql_db:
    name: zabbix
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql
  when: not result.stat.exists

- name: set new database password for mysql database
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    insertafter: "DBPassword="
    line: DBPassword={{ password_db }}

- name: replace zabbix config
  copy:
    src: nginx.conf
    dest: /etc/zabbix/
    owner: root
    group: root
    mode: '0644'

- name: enable and restart zabbix-server
  systemd:
    name: zabbix-server
    enabled: true
    masked: no
    state: restarted
  become: true

- name: enable and restart zabbix-agent
  systemd:
    name: zabbix-agent
    enabled: true
    masked: no
    state: restarted
  become: true

- name: enable and restart nginx
  systemd:
    name: nginx
    enabled: true
    masked: no
    state: restarted
  become: true

- name: enable and restart php
  systemd:
    name: php7.4-fpm
    enabled: true
    masked: no
    state: restarted
  become: true
