#cloud-config
package_update: true
package_upgrade: true
packages:
  - software-properties-common
  - ansible
runcmd:
  - add-apt-repository --yes --update ppa:ansible/ansible
  - apt install -y ansible
  - ansible --version
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${ssh_public_key}

