filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log

output.elasticsearch:
  hosts: ["http://192.168.10.50:9200"]

setup.kibana:
  host: "http://192.168.10.75:5601"
