# tasks file for roles/zabbix-agent
---
- name: Install zabbix-agent
  apt:
    name: zabbix-agent
    state: present

- name: Replace zabbix-agent configuration
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server=(.*)"
    line: "Server={{ zabbix_server }}"
    state: present

- name: Update zabbix-agent configuration
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive=(.*)"
    line: "ServerActive={{ zabbix_server }}"
    state: present

- name: Enable and restart zabbix-agent
  systemd:
    name: zabbix-agent
    enabled: true
    masked: no
    state: restarted
  become: true
